-- CreateTable
CREATE TABLE "Profile" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "ROLE" TEXT NOT NULL,
    "SKILLS" TEXT NOT NULL,
    "MARK" INTEGER NOT NULL DEFAULT 0,
    "GRADE" TEXT NOT NULL,
    "LIKES" INTEGER NOT NULL DEFAULT 0
);
